apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "istio-sidecar-restarter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "istio-sidecar-restarter.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  suspend: {{ .Values.suspend }}
  concurrencyPolicy: {{ .Values.concurrencyPolicy }}
  successfulJobsHistoryLimit: {{ .Values.successfulJobsHistoryLimit }}
  failedJobsHistoryLimit: {{ .Values.failedJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            {{- include "istio-sidecar-restarter.selectorLabels" . | nindent 12 }}
        spec:
          serviceAccountName: {{ include "istio-sidecar-restarter.serviceAccountName" . }}
          containers:
            - name: pod-restarter
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              args:
                {{- toYaml .Values.args | nindent 16 }}
              resources:
                {{- toYaml .Values.resources | nindent 16 }}
              securityContext:
                {{- toYaml .Values.securityContext | nindent 16 }}
          restartPolicy: {{ .Values.restartPolicy }}

