{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "istio-sidecar-restarter.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "istio-sidecar-restarter.labels" . | nindent 4 }}
{{- end }}

