name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Build binary
        run: |
          go build -v -o pod-restarter

      - name: Create and push tag
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          TAG="v$(date +'%Y%m%d%H%M%S')"
          git tag "$TAG"
          git push origin "$TAG"
